version: "3"

services:
  db:
    container_name: wtfood-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init/recipe-db.sql:/docker-entrypoint-initdb.d/init-recipe-db.sql
      - ./init/account-db.sql:/docker-entrypoint-initdb.d/init-account-db.sql
