GET /api/ingredients
Host: localhost:8080

###

GET /api/dishes/random
Host: localhost:8080

###

GET /api/dishes
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6InJvb3QifQ.zdYQIwmAhwpAPrIiPg05Qc7jlyY7ZkzicJgSF_Apw0I
